"""add cancellation to patient session new version

Revision ID: 04e0e82dcc5d
Revises: 5b04cf4e35cc
Create Date: 2026-05-13 19:55:00.214419

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04e0e82dcc5d'
down_revision: Union[str, Sequence[str], None] = '5b04cf4e35cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
