"""Add is_closed to patient sessions

Revision ID: 2010acb78342
Revises: 474817755118
Create Date: 2026-05-10 20:53:31.503285

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2010acb78342"
down_revision: Union[str, Sequence[str], None] = "474817755118"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_closed", sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.drop_column("is_closed")

    # ### end Alembic commands ###
