"""Add patient relations

Revision ID: 4a8bc534f1af
Revises: 9e8c57c34d2d
Create Date: 2026-05-01 16:08:05.320152

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8bc534f1af'
down_revision: Union[str, Sequence[str], None] = '9e8c57c34d2d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        pass
        #batch_op.add_column(sa.Column('birthdate', sa.Date(), nullable=True))
        #batch_op.alter_column('first_name',
        #       existing_type=sa.VARCHAR(length=64),
        #       type_=sa.String(length=100),
        #       existing_nullable=False)
        #batch_op.alter_column('last_name',
        #       existing_type=sa.VARCHAR(length=64),
        #       type_=sa.String(length=100),
        #       existing_nullable=False)
        #batch_op.alter_column('gender',
        #       existing_type=sa.VARCHAR(length=16),
        #       type_=sa.String(length=20),
        #       nullable=True)
        #batch_op.alter_column('notes',
        #       existing_type=sa.TEXT(),
        #       nullable=True)
        #batch_op.create_index(batch_op.f('ix_patients_id'), ['id'], unique=False)

        ## ENTFERNT, da SQLite den Namen für Foreign Keys nicht kennt und beim Drop der Column automatisch aufräumt:
        ## batch_op.drop_constraint(None, type_='foreignkey')

        #batch_op.drop_column('insurance_name')
        #batch_op.drop_column('birthdate')
        #batch_op.drop_column('phone')
        #batch_op.drop_column('street')
        #batch_op.drop_column('created_at')
        #batch_op.drop_column('is_active')
        #batch_op.drop_column('city')
        #batch_op.drop_column('postal_code')
        #batch_op.drop_column('email')
        #batch_op.drop_column('therapist_id')
        #batch_op.drop_column('insurance_number')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('insurance_number', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('therapist_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('postal_code', sa.VARCHAR(length=16), nullable=False))
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=64), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.BOOLEAN(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('street', sa.VARCHAR(length=128), nullable=False))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=32), nullable=False))
        batch_op.add_column(sa.Column('birthdate', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('insurance_name', sa.VARCHAR(length=128), nullable=False))

        # ENTFERNT, passend zur Änderung im Upgrade-Block:
        # batch_op.create_foreign_key(None, 'users', ['therapist_id'], ['id'])

        batch_op.drop_index(batch_op.f('ix_patients_id'))
        batch_op.alter_column('notes',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('gender',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=16),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###