"""add cancellation to patient session new version

Revision ID: 5b04cf4e35cc
Revises: d1e97c2d314b
Create Date: 2026-05-13 19:47:57.125195

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b04cf4e35cc'
down_revision: Union[str, Sequence[str], None] = 'd1e97c2d314b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Enum('OPEN', 'COMPLETED', 'INVOICED', 'PAID', 'CANCELLED', name='sessionstatus'), nullable=False, server_default='Offen'))
        batch_op.add_column(sa.Column('parent_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_patient_sessions_parent', 'patient_sessions', ['parent_id'], ['id'])
        batch_op.drop_column('is_closed')
        batch_op.drop_column('is_paid')
        batch_op.drop_column('is_invoiced')
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_invoiced', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_paid', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('is_closed', sa.BOOLEAN(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
