"""Add account number to pyment method

Revision ID: 5e6282f610c2
Revises: 77f490ac370d
Create Date: 2026-05-10 19:44:56.400220

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5e6282f610c2"
down_revision: Union[str, Sequence[str], None] = "77f490ac370d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_methods", schema=None) as batch_op:
        batch_op.add_column(sa.Column("account_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_payment_methods_account_id",
            "accounting_accounts",
            ["account_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payment_methods", schema=None) as batch_op:
        batch_op.drop_constraint("fk_payment_methods_account_id", type_="foreignkey")
        batch_op.drop_column("account_id")

    # ### end Alembic commands ###
