"""add pathes for uploads (patients and misc) in settings

Revision ID: 695219a9111b
Revises: 1695478e6ed7
Create Date: 2026-05-19 10:06:02.682884

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '695219a9111b'
down_revision: Union[str, Sequence[str], None] = '1695478e6ed7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_path_patient_documents', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('upload_path_misc', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('upload_path_misc')
        batch_op.drop_column('upload_path_patient_documents')

    # ### end Alembic commands ###
