"""Add accounting foundation

Revision ID: 6e8297c615b0
Revises: 2f472fa2bfdc
Create Date: 2026-05-08 19:00:10.307906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e8297c615b0'
down_revision: Union[str, Sequence[str], None] = '2f472fa2bfdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_class', sa.Integer(), nullable=False),
    sa.Column('account_group', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number')
    )
    with op.batch_alter_table('accounting_accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_accounts_id'), ['id'], unique=False)

    op.create_table('accounting_fiscal_years',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_fiscal_years_id'), ['id'], unique=False)

    op.create_table('accounting_journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fiscal_year_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fiscal_year_id'], ['accounting_fiscal_years.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_journal_entries_id'), ['id'], unique=False)

    op.create_table('accounting_journal_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_entry_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounting_accounts.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['accounting_journal_entries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounting_journal_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounting_journal_lines_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_journal_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_journal_lines_id'))

    op.drop_table('accounting_journal_lines')
    with op.batch_alter_table('accounting_journal_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_journal_entries_id'))

    op.drop_table('accounting_journal_entries')
    with op.batch_alter_table('accounting_fiscal_years', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_fiscal_years_id'))

    op.drop_table('accounting_fiscal_years')
    with op.batch_alter_table('accounting_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounting_accounts_id'))

    op.drop_table('accounting_accounts')
    # ### end Alembic commands ###
