"""Add invoice details to patient sessions

Revision ID: 77e39e5e21e9
Revises: 2010acb78342
Create Date: 2026-05-11 19:06:30.879618

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77e39e5e21e9"
down_revision: Union[str, Sequence[str], None] = "2010acb78342"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("is_invoiced", sa.Boolean(), nullable=True))
        batch_op.add_column(
            sa.Column("invoice_number", sa.String(length=50), nullable=True)
        )
        batch_op.add_column(sa.Column("invoice_version", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.drop_column("invoice_version")
        batch_op.drop_column("invoice_number")
        batch_op.drop_column("is_invoiced")

    # ### end Alembic commands ###
