"""Add session link to journal

Revision ID: 77f490ac370d
Revises: e82cc0ac58b0
Create Date: 2026-05-09 08:08:31.278171

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "77f490ac370d"
down_revision: Union[str, Sequence[str], None] = "e82cc0ac58b0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounting_journal_entries", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("patient_session_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_journal_session", "patient_sessions", ["patient_session_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("accounting_journal_entries", schema=None) as batch_op:
        batch_op.drop_constraint("fk_journal_session", type_="foreignkey")
        batch_op.drop_column("patient_session_id")

    # ### end Alembic commands ###
