"""Add company profile and templates

Revision ID: 7a8c54bed8cc
Revises: 859dd94d9f54
Create Date: 2026-05-06 17:01:20.384971

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7a8c54bed8cc"
down_revision: Union[str, Sequence[str], None] = "859dd94d9f54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_profiles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("zip_code", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.Column("iban", sa.String(), nullable=True),
        sa.Column("bank_name", sa.String(), nullable=True),
        sa.Column("logo_path", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_company_profiles_id"), ["id"], unique=False
        )

    op.create_table(
        "document_templates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("doc_type", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("file_path", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_templates", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_document_templates_id"), ["id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("document_templates", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_document_templates_id"))

    op.drop_table("document_templates")
    with op.batch_alter_table("company_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_company_profiles_id"))

    op.drop_table("company_profiles")
    # ### end Alembic commands ###
