"""Add user_id to PatientSession

Revision ID: 7eb65b8f74b2
Revises: e06f66db52eb
Create Date: 2026-05-08 11:03:02.612138

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7eb65b8f74b2"
down_revision: Union[str, Sequence[str], None] = "e06f66db52eb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            "fk_patient_sessions_user_id", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("patient_sessions", schema=None) as batch_op:
        batch_op.drop_constraint("fk_patient_sessions_user_id", type_="foreignkey")
        batch_op.drop_column("user_id")

    # ### end Alembic commands ###
