"""Add backup automation settings

Revision ID: 9e8c57c34d2d
Revises: 4bc7a5e918bd
Create Date: 2026-05-01 15:11:11.174168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e8c57c34d2d'
down_revision: Union[str, Sequence[str], None] = '4bc7a5e918bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        #batch_op.add_column(sa.Column('backup_on_close', sa.Boolean(), nullable=True))
        #batch_op.add_column(sa.Column('backup_schedule', sa.String(length=50), nullable=True))
        #batch_op.add_column(sa.Column('last_backup', sa.DateTime(), nullable=True))
        pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('last_backup')
        batch_op.drop_column('backup_schedule')
        batch_op.drop_column('backup_on_close')

    # ### end Alembic commands ###
