"""Add app_settings table

Revision ID: bda065a5bda6
Revises: 043122d804e7
Create Date: 2026-05-01 14:33:57.852145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bda065a5bda6'
down_revision: Union[str, Sequence[str], None] = '043122d804e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_log_entries_id'))
        batch_op.drop_index(batch_op.f('ix_log_entries_level'))
        batch_op.drop_index(batch_op.f('ix_log_entries_timestamp'))

    op.drop_table('log_entries')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_entries',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('level', sa.VARCHAR(length=20), nullable=True),
    sa.Column('module', sa.VARCHAR(length=100), nullable=True),
    sa.Column('message', sa.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_log_entries_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_entries_id'), ['id'], unique=False)

    # ### end Alembic commands ###
