"""add cancellation to patient session

Revision ID: d1e97c2d314b
Revises: 059215fa237b
Create Date: 2026-05-13 16:59:40.775137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1e97c2d314b'
down_revision: Union[str, Sequence[str], None] = '059215fa237b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_cancelled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('is_cancelled')

    # ### end Alembic commands ###
