"""add pdf_password_enc in settings

Revision ID: d527451a44aa
Revises: c3d4e5f6a1b2
Create Date: 2026-05-19 15:29:25.216877

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd527451a44aa'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6a1b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_files', schema=None) as batch_op:
        batch_op.alter_column('encryption_type',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('PDF_PASSWORD', 'AES_GCM', name='encryptiontype'),
               existing_nullable=False,
               existing_server_default=sa.text("'pdf_password'"))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_files', schema=None) as batch_op:
        batch_op.alter_column('encryption_type',
               existing_type=sa.Enum('PDF_PASSWORD', 'AES_GCM', name='encryptiontype'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pdf_password'"))

    # ### end Alembic commands ###
