"""Add VAT, payment terms and bank details

Revision ID: e06f66db52eb
Revises: c6b3dad46797
Create Date: 2026-05-07 20:33:45.919621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e06f66db52eb'
down_revision: Union[str, Sequence[str], None] = 'c6b3dad46797'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('payment_terms_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('payment_terms_mode', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('account_number', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bic_swift', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('company_profiles', schema=None) as batch_op:
        batch_op.drop_column('bic_swift')
        batch_op.drop_column('account_number')
        batch_op.drop_column('payment_terms_mode')
        batch_op.drop_column('payment_terms_days')
        batch_op.drop_column('vat_number')

    # ### end Alembic commands ###
