"""Add booking_text to session

Revision ID: e82cc0ac58b0
Revises: 6e8297c615b0
Create Date: 2026-05-08 19:58:55.144459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82cc0ac58b0'
down_revision: Union[str, Sequence[str], None] = '6e8297c615b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient_sessions', schema=None) as batch_op:
        batch_op.drop_column('booking_text')

    # ### end Alembic commands ###
