"""Add upload paths

Revision ID: f99cb06aeb09
Revises: 7a8c54bed8cc
Create Date: 2026-05-06 17:09:43.473547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f99cb06aeb09'
down_revision: Union[str, Sequence[str], None] = '7a8c54bed8cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_path_logos', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('upload_path_templates', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_settings', schema=None) as batch_op:
        batch_op.drop_column('upload_path_templates')
        batch_op.drop_column('upload_path_logos')

    # ### end Alembic commands ###
